security:
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /login
            
           
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
#        - { path: ^/, roles: ROLE_VIEW_PERSON }
    providers:
        administrator:
            entity: {class: AppBundle:Utilisateur}
#        in_memory:
#            memory:
#                users:
#                    ryan: { password: ryanpass, roles: 'ROLE_USER' }
#                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Utilisateur:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
        
           